// One color meaning per token role, shared by cards, table, chart and drawer.
// If input renders orange in one place and green in another, the operator has to
// re-read the legend on every surface, so these live in exactly one file.

export const TOKEN_ROLE = {
  input: {
    label: "Input",
    text: "text-primary",
    bg: "bg-primary",
    hex: "#E56A4A",
    hint: "Prompt tokens sent upstream, including cached tokens.",
  },
  cached: {
    label: "Cached input",
    text: "text-info",
    bg: "bg-info",
    hex: "#3B82F6",
    hint: "Prompt tokens served from the provider cache, billed at a reduced rate.",
  },
  output: {
    label: "Output",
    text: "text-success",
    bg: "bg-success",
    hex: "#10B981",
    hint: "Tokens generated by the model, reasoning included.",
  },
  cost: {
    label: "Estimated cost",
    text: "text-warning",
    bg: "bg-warning",
    hex: "#F59E0B",
    hint: "Estimated from configured pricing, not actual provider billing.",
  },
};

/**
 * Shares for the composition bar. Input is the whole prompt, of which cached is
 * a part, so the cached share is subtracted from the uncached remainder.
 */
export function tokenComposition({ inputTokens = 0, outputTokens = 0, cachedTokens = 0 }) {
  const input = Math.max(0, inputTokens || 0);
  const output = Math.max(0, outputTokens || 0);
  const cached = Math.min(Math.max(0, cachedTokens || 0), input);
  const total = input + output;
  if (total <= 0) return { total: 0, segments: [] };
  const segments = [
    { role: "input", value: input - cached },
    { role: "cached", value: cached },
    { role: "output", value: output },
  ].filter((s) => s.value > 0);
  return {
    total,
    segments: segments.map((s) => ({ ...s, pct: (s.value / total) * 100 })),
  };
}

/** Cache hit rate over prompt tokens. */
export function cacheHitRate({ inputTokens = 0, cachedTokens = 0 }) {
  if (!inputTokens) return null;
  return (Math.min(cachedTokens || 0, inputTokens) / inputTokens) * 100;
}
